"""Shared full workbench export for hand-tuned curated dark themes."""

from __future__ import annotations

from typing import Any


def build_curated_dark_vscode_theme(
    *,
    display_name: str,
    roles: dict[str, str],
    chrome: dict[str, str],
) -> dict[str, Any]:
    r = roles
    c = chrome
    bg, fg = r["background"], r["foreground"]
    surf, muted = r["surface"], r["muted"]
    a1, a2 = r["accent_primary"], r["accent_secondary"]
    s1, s2, s3 = r["syntax_1"], r["syntax_2"], r["syntax_3"]
    s4, s5, s6 = r["syntax_4"], r["syntax_5"], r["syntax_6"]
    sel = c["selection"]

    return {
        "name": display_name,
        "type": "dark",
        "colors": {
            "editor.background": bg,
            "editor.foreground": fg,
            "editorCursor.foreground": a1,
            "editor.lineHighlightBackground": surf + "55",
            "editor.selectionBackground": a2 + "44",
            "editor.inactiveSelectionBackground": muted + "44",
            "editor.selectionHighlightBackground": a2 + "28",
            "editor.wordHighlightBackground": a1 + "28",
            "editor.wordHighlightStrongBackground": a1 + "40",
            "editorIndentGuide.background1": muted + "44",
            "editorIndentGuide.activeBackground1": a1 + "66",
            "editorWhitespace.foreground": muted + "55",
            "editorLineNumber.foreground": muted + "88",
            "editorLineNumber.activeForeground": a1,
            "editorGutter.background": bg,
            "activityBar.background": c["shell"],
            "activityBar.foreground": fg,
            "activityBar.border": r["border"] + "44",
            "activityBarBadge.background": a1,
            "activityBarBadge.foreground": bg,
            "sideBar.background": c["sidebar"],
            "sideBar.foreground": fg,
            "sideBar.border": r["border"] + "33",
            "sideBarTitle.foreground": fg,
            "sideBarSectionHeader.background": c["shell"],
            "sideBarSectionHeader.foreground": a1,
            "statusBar.background": surf,
            "statusBar.foreground": fg,
            "statusBar.border": r["border"] + "44",
            "titleBar.activeBackground": c["shell"],
            "titleBar.activeForeground": fg,
            "titleBar.inactiveBackground": c["shell"],
            "titleBar.inactiveForeground": muted,
            "editorGroupHeader.tabsBackground": c["shell"],
            "editorGroup.border": r["border"] + "44",
            "tab.inactiveBackground": c["shell"],
            "tab.inactiveForeground": muted,
            "tab.activeBackground": c["tab_active"],
            "tab.activeForeground": fg,
            "tab.border": c["shell"],
            "tab.lastPinnedBorder": a1 + "66",
            "panel.background": c["sidebar"],
            "panel.border": r["border"] + "44",
            "panelTitle.activeForeground": fg,
            "panelTitle.inactiveForeground": muted,
            "input.background": c["prompt"],
            "input.foreground": fg,
            "input.border": a1 + "66",
            "input.placeholderForeground": a2 + "AA",
            "inputOption.activeBackground": sel + "55",
            "inputOption.activeBorder": a1 + "00",
            "dropdown.background": c["prompt"],
            "dropdown.foreground": fg,
            "dropdown.border": r["border"] + "55",
            "quickInput.background": c["prompt"],
            "quickInput.foreground": fg,
            "quickInputList.focusBackground": sel + "BB",
            "list.activeSelectionBackground": sel + "AA",
            "list.inactiveSelectionBackground": sel + "55",
            "list.hoverBackground": sel + "66",
            "list.focusBackground": sel + "AA",
            "list.activeSelectionForeground": fg,
            "list.inactiveSelectionForeground": fg,
            "list.focusForeground": fg,
            "list.highlightForeground": a1,
            "pickerGroup.foreground": a1,
            "pickerGroup.border": muted + "55",
            "editorWidget.background": c["prompt"],
            "editorWidget.foreground": fg,
            "editorWidget.border": r["border"] + "55",
            "editorHoverWidget.background": c["prompt"],
            "editorHoverWidget.foreground": fg,
            "editorHoverWidget.border": r["border"] + "66",
            "editorSuggestWidget.background": c["prompt"],
            "editorSuggestWidget.foreground": fg,
            "editorSuggestWidget.border": r["border"] + "55",
            "editorSuggestWidget.selectedBackground": sel + "88",
            "selection.background": sel + "66",
            "focusBorder": a1,
            "badge.background": a1,
            "badge.foreground": bg,
            "button.background": a1,
            "button.foreground": bg,
            "button.hoverBackground": a2,
            "terminal.background": bg,
            "terminal.foreground": fg,
            "terminal.ansiBlack": c["shell"],
            "terminal.ansiRed": s6,
            "terminal.ansiGreen": s1,
            "terminal.ansiYellow": s3,
            "terminal.ansiBlue": a1,
            "terminal.ansiMagenta": s2,
            "terminal.ansiCyan": s5,
            "terminal.ansiWhite": fg,
            "terminal.ansiBrightRed": s4,
            "terminal.ansiBrightGreen": a2,
            "terminal.ansiBrightYellow": s3,
            "terminal.ansiBrightBlue": a1,
            "terminal.ansiBrightMagenta": s2,
            "terminal.ansiBrightCyan": s5,
            "terminal.ansiBrightWhite": fg,
        },
        "tokenColors": [
            {"scope": ["comment", "punctuation.definition.comment"], "settings": {"foreground": muted, "fontStyle": "italic"}},
            {"scope": ["keyword", "storage", "storage.type"], "settings": {"foreground": s4}},
            {"scope": ["entity.name.function", "support.function"], "settings": {"foreground": s5}},
            {"scope": ["string", "constant.other.symbol"], "settings": {"foreground": s1}},
            {"scope": ["constant.numeric", "constant.language"], "settings": {"foreground": s3}},
            {"scope": ["variable", "meta.definition.variable.name"], "settings": {"foreground": fg}},
            {"scope": ["entity.name.type", "support.type"], "settings": {"foreground": s2}},
            {"scope": ["invalid", "invalid.illegal"], "settings": {"foreground": s6}},
            {"scope": ["support.class.component.js", "entity.name.type.class.ts"], "settings": {"foreground": s2}},
            {"scope": ["entity.name.type.module.js", "support.type.primitive.ts"], "settings": {"foreground": s4}},
            {"scope": ["storage.type.function.python", "entity.name.function.decorator.python"], "settings": {"foreground": s5}},
            {"scope": ["support.type.python", "entity.name.class.python"], "settings": {"foreground": s2}},
            {"scope": ["support.type.property-name.json"], "settings": {"foreground": a2}},
            {"scope": ["constant.language.json"], "settings": {"foreground": s4}},
            {"scope": ["markup.heading.markdown", "markup.bold.markdown"], "settings": {"foreground": a1}},
            {"scope": ["markup.italic.markdown", "markup.inline.raw.string.markdown"], "settings": {"foreground": s1}},
            {"scope": ["support.function.builtin.shell", "keyword.operator.pipe.shell"], "settings": {"foreground": s5}},
            {"scope": ["variable.other.normal.shell"], "settings": {"foreground": s2}},
        ],
    }
